apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: mxkafka
  name: mxuser
  namespace: maskafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: prefix
          type: topic
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: prefix
          type: group
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple
