apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mxkafka
  namespace: maskafka 
spec:
  kafka:
    version: 3.0.0
    resources:
      requests:
        memory: 4Gi
        cpu: "2"
      limits:
        memory: 4Gi
        cpu: "2"
    jvmOptions:
      -Xms: 3072m
      -Xmx: 3072m
    replicas: 1   
    listeners:
      - authentication:
          type: scram-sha-512        
        name: external
        networkPolicyPeers:
          - namespaceSelector: {}
        port: 9093
        tls: true
        type: route
      - authentication:
          type: scram-sha-512
        name: plain
        networkPolicyPeers:
          - namespaceSelector: {}
        port: 9092
        tls: false
        type: internal
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      log.retention.hours: 24
      log.retention.bytes: 1073741824
      log.segment.bytes: 268435456
      log.cleaner.enable: true
      log.cleanup.policy: delete
      auto.create.topics.enable: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: rook-cephfs
        size: 100Gi
        deleteClaim: true
    authorization:
      type: simple
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    storage:
      type: persistent-claim
      class: rook-cephfs
      size: 10Gi
      deleteClaim: true
  entityOperator:
    template: 
      topicOperatorContainer:
        env:
        - name: STRIMZI_APPLICATION_ID
          value: __strimzi-top-mxkstreams
    topicOperator: {}
    userOperator: {}
