apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sqin
  namespace: mxkafka
  labels:
    strimzi.io/cluster: mxkafka
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 1
  replicas: 1
